
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 44
#define YY_END_OF_BUFFER 45
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[148] =
    {   0,
       20,   20,    0,    0,   32,   32,   45,   43,   25,   20,
       24,   29,   20,   26,   34,   40,   42,   24,   33,   41,
       24,   27,   23,   35,   24,   26,   26,   43,   26,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   39,
       44,    1,   32,   31,   44,   25,   35,   20,   20,   15,
       26,   36,   38,   28,   27,    0,    0,   22,    0,    0,
       26,    0,   19,    0,   26,   26,   26,   26,   26,   26,
        3,   11,   26,   26,   26,   26,   26,   26,   37,    0,
        1,   32,   31,    0,   32,   30,   32,   28,    0,    0,
       28,    0,    0,   21,    0,   26,    0,   26,   26,   26,

       26,   10,   26,   26,   26,   26,   16,   26,   26,   30,
       32,   31,    0,    0,   28,    0,    2,   26,   26,   26,
        4,   26,   26,   26,   14,   18,   26,    0,   32,   32,
        7,   17,   26,   26,   26,   13,   26,    6,   26,    5,
       26,   12,   26,   26,    8,    9,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    7,    8,    9,   10,   11,
       11,    8,   12,   13,   12,   14,    8,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   11,   16,   17,
       18,   17,   16,    8,   19,   19,   19,   19,   20,   19,
       19,   19,   19,   19,   19,   21,   19,   22,   19,   19,
       19,   19,   19,   19,   23,   19,   19,   19,   19,   19,
       11,   24,   11,   11,   19,    1,   25,   26,   27,   19,

       28,   29,   19,   30,   31,   19,   32,   33,   19,   34,
       35,   19,   19,   36,   37,   38,   39,   40,   41,   19,
       42,   19,   11,   43,   11,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[44] =
    {   0,
        1,    1,    1,    1,    1,    1,    2,    1,    1,    1,
        1,    1,    1,    1,    2,    1,    1,    1,    2,    2,
        2,    2,    2,    1,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    1
    } ;

static const flex_int16_t yy_base[159] =
    {   0,
        0,    0,  224,  223,   41,   42,  225,  228,  222,  228,
      205,  228,  219,  214,  202,  210,  228,  228,  200,  228,
      202,   34,   49,  198,  197,    0,  191,   54,  177,   28,
      179,   29,   38,  176,  182,  181,  172,  179,  176,  162,
      201,  228,   56,  228,   68,  201,  228,  199,  228,    0,
        0,  228,  228,   61,   63,   67,   82,  228,  198,   84,
      179,   90,  228,  196,  170,  159,  162,  158,  158,  159,
        0,    0,  165,  153,  157,  147,  157,  156,  228,  183,
      228,   92,  228,   96,   98,  228,  102,   93,   97,  170,
      169,  180,  108,  228,  179,  160,  177,  154,  151,  139,

      148,    0,  148,  149,  134,  143,    0,  138,  116,  228,
      112,  145,  117,  132,  130,  141,    0,  111,  112,  110,
      109,  101,  105,  101,    0,    0,  107,  131,  122,  126,
        0,    0,   99,  103,   99,    0,   84,    0,   55,    0,
       40,    0,   41,   24,    0,    0,  228,  150,  152,  154,
       48,  156,  158,  160,  162,  164,  166,  168
    } ;

static const flex_int16_t yy_def[159] =
    {   0,
      147,    1,  148,  148,  149,  149,  147,  147,  147,  147,
      147,  147,  150,  151,  147,  147,  147,  147,  147,  147,
      147,  147,  147,  147,  147,  151,  151,  147,  151,  151,
      151,  151,  151,  151,  151,  151,  151,  151,  151,  147,
      152,  147,  153,  147,  153,  147,  147,  150,  147,  151,
      151,  147,  147,  147,  147,  147,  147,  147,  154,  147,
      151,  147,  147,  155,  151,  151,  151,  151,  151,  151,
      151,  151,  151,  151,  151,  151,  151,  151,  147,  152,
      147,  153,  147,  153,  153,  147,  156,  147,  147,  147,
      147,  154,  147,  147,  157,  151,  155,  151,  151,  151,

      151,  151,  151,  151,  151,  151,  151,  151,  151,  147,
      156,  158,  156,  147,  147,  157,  151,  151,  151,  151,
      151,  151,  151,  151,  151,  151,  151,  158,  156,  156,
      151,  151,  151,  151,  151,  151,  151,  151,  151,  151,
      151,  151,  151,  151,  151,  151,    0,  147,  147,  147,
      147,  147,  147,  147,  147,  147,  147,  147
    } ;

static const flex_int16_t yy_nxt[272] =
    {   0,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       18,   19,   20,   21,   22,   23,   24,   25,   26,   26,
       26,   27,   26,   28,   26,   29,   30,   31,   32,   26,
       33,   26,   34,   26,   26,   35,   36,   37,   26,   38,
       39,   26,   40,   44,   44,   44,   44,   54,   55,   51,
       57,   58,   66,   56,   59,   62,   63,  146,   83,   64,
       83,   56,   67,   69,   45,   45,   71,   70,  145,   85,
       86,   72,   60,   87,  144,   88,   54,   55,   90,   84,
       89,   91,   56,   57,   58,   93,   94,   59,   89,   95,
       56,   62,   63,  143,   83,   64,   83,   85,   86,   85,

      110,   87,   83,   87,  110,   60,  112,   88,  114,   93,
       94,  115,   89,   95,  110,   84,  112,  142,  129,   86,
       89,   84,  130,  129,  110,  113,  112,  130,  110,  141,
      112,  140,  139,   86,  138,  113,  137,  136,  135,  134,
      133,  132,  131,   94,  115,  113,  115,   86,  127,  113,
       41,   41,   43,   43,   48,   48,   80,   80,   82,   82,
       92,   92,   97,   97,  111,  111,  116,  116,  128,  128,
      126,  125,  124,  123,  122,  121,  120,  119,  118,   63,
      117,   94,   58,   91,   91,   81,  109,  108,  107,  106,
      105,  104,  103,  102,  101,  100,   99,   98,   63,   96,

       58,   49,   46,   81,   79,   78,   77,   76,   75,   74,
       73,   68,   65,   61,   47,   47,   54,   52,   53,   52,
       50,   49,   47,   46,  147,   42,   42,    7,  147,  147,
      147,  147,  147,  147,  147,  147,  147,  147,  147,  147,
      147,  147,  147,  147,  147,  147,  147,  147,  147,  147,
      147,  147,  147,  147,  147,  147,  147,  147,  147,  147,
      147,  147,  147,  147,  147,  147,  147,  147,  147,  147,
      147
    } ;

static const flex_int16_t yy_chk[272] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    5,    6,    5,    6,   22,   22,  151,
       23,   23,   30,   22,   23,   28,   28,  144,   43,   28,
       43,   22,   30,   32,    5,    6,   33,   32,  143,   45,
       45,   33,   23,   45,  141,   54,   55,   55,   56,   43,
       54,   56,   55,   57,   57,   60,   60,   57,   54,   60,
       55,   62,   62,  139,   82,   62,   82,   84,   84,   85,

       85,   84,   85,   85,   87,   57,   87,   88,   89,   93,
       93,   89,   88,   93,  111,   82,  111,  137,  113,  113,
       88,   85,  113,  129,  129,   87,  129,  129,  130,  135,
      130,  134,  133,  128,  127,  111,  124,  123,  122,  121,
      120,  119,  118,  116,  115,  129,  114,  112,  109,  130,
      148,  148,  149,  149,  150,  150,  152,  152,  153,  153,
      154,  154,  155,  155,  156,  156,  157,  157,  158,  158,
      108,  106,  105,  104,  103,  101,  100,   99,   98,   97,
       96,   95,   92,   91,   90,   80,   78,   77,   76,   75,
       74,   73,   70,   69,   68,   67,   66,   65,   64,   61,

       59,   48,   46,   41,   40,   39,   38,   37,   36,   35,
       34,   31,   29,   27,   25,   24,   21,   19,   16,   15,
       14,   13,   11,    9,    7,    4,    3,  147,  147,  147,
      147,  147,  147,  147,  147,  147,  147,  147,  147,  147,
      147,  147,  147,  147,  147,  147,  147,  147,  147,  147,
      147,  147,  147,  147,  147,  147,  147,  147,  147,  147,
      147,  147,  147,  147,  147,  147,  147,  147,  147,  147,
      147
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "scan.l"
/*
   scan.l -- Algae lexical scanner.

   Copyright (C) 1994-2002  K. Scott Hunziker.
   Copyright (C) 1990-1994  The Boeing Company.

   See the file COPYING for license, warranty, and permission details.
*/
/* $Id: scan.l,v 1.12 2003/08/07 02:34:09 ksh Exp $ */
#line 13 "scan.l"

#define  PSR_DATA_HERE

#include "algae.h"
#include <string.h>
#include <ctype.h>
#include "entity.h"
#include "psr.h"
#include "code.h"
#include "parse.h"
#include "mem.h"
#include "pmem.h"
#include "exception.h"
#include "message.h"
#include "print.h"
#include "printf.h"
#include "error.h"

int PROTO(yylex, (YYSTYPE *lexval)) ;
#define YY_DECL int yylex( lexval ) YYSTYPE *lexval;

static int PROTO( line_input, ( char *buff, int buffer_size ) );

#if HAVE_LIBREADLINE
extern int use_readline;

char *PROTO( readline, ( char *prompt ) );
char *PROTO( readline_fgets, ( char *s, int n, char *prompt ) );
#endif /* HAVE_LIBREADLINE */

int issue_prompt;	/* Give prompt if set. */

static char *PROTO(rm_escape, (char *)) ;
static void PROTO(add_to_string, (char *,int)) ;
static char *PROTO(get_string, (void)) ;


static int next_offset ;
static int max_size ; /* max size string curr_line will hold */
static int continuing ; /* helps with prompt */
static int eof_flag ;   /* only used when non-interactive,
	to help when last line lacks a newline */




#define  ADJ_OFFSET()    curr_offset = next_offset ;\
			 next_offset += yyleng 

int yywrap() { return 1; }

/* this needs to be expanded for non-interactive input */
#undef  YY_INPUT
#define YY_INPUT(buff, result, max_size) \
	do {\
	    result = line_input((char *)buff, max_size) ; \
	    if ( flush_flag )\
	    { flush_flag = 0 ; BEGIN(0) ; }}while(0)

static char *input_string;	/* input, if commands not coming from file */ 

#define FGETS(s, n, stream) \
  ((stream) ? fgets (s, n, stream) : sgets (s, n, &input_string))

/*
 * Like fgets(3), except it reads from the string pointed to by `c' and
 * then modifies that string to point to the remainder.
 */
static char *
sgets (s, n, c)
     char *s;
     int n;
     char **c;
{
  char *e, *p;
  int i;

  p = *c;
  if (!*p) return NULL;

  e = strchr (p, '\n');
  i = e ? e-p+1 : strlen (p);
  n--;
  if (i > n) i = n;
  memcpy (s, p, i);
  s[i] = '\0';
  *c = p+i;
  return s;
}

static int
line_input (buff, buffer_size)
     char *buff;
     int buffer_size;
{
  int len;
  char *prompt, *more_input;

  SIGINT_RAISE_ON ();

again:
  if (issue_prompt && yyin)
    {
      if (continuing)
	{
	  prompt = get_prompt (1);
	  continuing = 0;
	}
      else
	prompt = get_prompt (brace_cnt || flow_cnt);

#if HAVE_LIBREADLINE
      if (use_readline)
	more_input = readline_fgets (buff, buffer_size, prompt);
      else
#endif
	{
#ifdef VAX_VMS
	  xputc ('\n', stderr);
#endif
	  xfputs (prompt, stderr);
	  more_input = fgets (buff, buffer_size, yyin);
	}
      FREE (prompt);
    }
  else
    more_input = FGETS (buff, buffer_size, yyin);

  if (more_input)
    {
      curr_line_no++;
      len = strlen (buff);

      if (len > max_size)
	{
	  if (max_size)
	    FREE (curr_line);
	  curr_line = MALLOC (len + 1);
	  max_size = len;
	}

      (void) strcpy (curr_line, buff);
      next_offset = 0;
    }
  else
    {
      if (errno == EINTR)
	{
	  errno = 0;
	  goto again;
	}
      else if (yyin && ferror (yyin))
	{
	  p_error ("%s", strerror (errno));
	  exit (1);
	}
      else			/* EOF */
	len = 0;
    }

  SIGINT_RAISE_OFF ();
  return len;
}


#if HAVE_LIBREADLINE
extern void PROTO (add_history, (char * string));

char *
readline_fgets( s, n, prompt )
  char *s;
  int n;
  char *prompt;
{
    char *line_read = readline( prompt );
    if ( line_read ) {
	if ( *line_read ) add_history( line_read );
	strncpy( s, line_read, n-2 );
	s[n-2] = '\0';
	n = strlen( s );
	s[n] = '\n';
	s[n+1] = '\0';
	free( line_read );
	line_read = s;
    }

    return line_read;
}
#endif /* HAVE_LIBREADLINE */      
	

#line 751 "lex.yy.c"

#line 753 "lex.yy.c"

#define INITIAL 0
#define FLUSH 1
#define STRINGING 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 231 "scan.l"


#line 234 "scan.l"
	/* this always gets done */
	if ( flush_flag )
	{ continuing = 0 ; BEGIN(FLUSH) ; }

#line 980 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 148 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 228 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 238 "scan.l"
{ /* eat the line */
			  BEGIN(0) ;
			}
	YY_BREAK
/*----------------------------------------*/
/* keywords are hardwired into the scanner */
case 2:
YY_RULE_SETUP
#line 248 "scan.l"
{ ADJ_OFFSET() ; return _NULL ; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 249 "scan.l"
{ ADJ_OFFSET() ; return IF ; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 250 "scan.l"
{ ADJ_OFFSET() ; return ELSE ; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 251 "scan.l"
{ ADJ_OFFSET() ; return ELSEIF ; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 252 "scan.l"
{ ADJ_OFFSET() ; return WHILE ; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 253 "scan.l"
{ ADJ_OFFSET() ; return BREAK ; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 254 "scan.l"
{ ADJ_OFFSET() ; return CONTINUE ; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 255 "scan.l"
{ ADJ_OFFSET() ; return FUNCTION_ ; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 256 "scan.l"
{ ADJ_OFFSET() ; return FOR ; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 257 "scan.l"
{ ADJ_OFFSET() ; return IN ; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 258 "scan.l"
{ ADJ_OFFSET() ; return RETURN ; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 259 "scan.l"
{ ADJ_OFFSET() ; return LOCAL ; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 260 "scan.l"
{ ADJ_OFFSET() ; return SELF  ; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 261 "scan.l"
{ ADJ_OFFSET() ; return SYMBOL_TABLE ; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 262 "scan.l"
{ ADJ_OFFSET() ; return TRY  ; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 263 "scan.l"
{ ADJ_OFFSET() ; return CATCH  ; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 264 "scan.l"
{ ADJ_OFFSET() ; return VEIL  ; }
	YY_BREAK
case 19:
/* rule 19 can match eol */
YY_RULE_SETUP
#line 266 "scan.l"
{ continuing = 1 ; }
	YY_BREAK
case 20:
/* rule 20 can match eol */
YY_RULE_SETUP
#line 268 "scan.l"
{ ADJ_OFFSET() ;
		  if ( brace_cnt == 0 ) return '\n' ;
		}
	YY_BREAK
case 21:
/* rule 21 can match eol */
YY_RULE_SETUP
#line 272 "scan.l"
{ ADJ_OFFSET() ;
			continuing = 1 ;
			lexval->ival = 0 ;
			return *yytext ;
		    }
	YY_BREAK
case 22:
/* rule 22 can match eol */
YY_RULE_SETUP
#line 278 "scan.l"
{ ADJ_OFFSET() ;
			lexval->ival = 1 ;
			return *yytext ;
		      }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 283 "scan.l"
{ ADJ_OFFSET() ; 
		  lexval->ival = 0 ;
		  return *yytext ;
		}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 288 "scan.l"
{ ADJ_OFFSET() ; return *yytext ; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 290 "scan.l"
{ ADJ_OFFSET() ; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 292 "scan.l"
{ ADJ_OFFSET() ;
		  lexval->id_name = strcpy(MALLOC(yyleng+1),yytext) ;
		  return ID ;
		}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 297 "scan.l"
{ ADJ_OFFSET() ;
		  errno = 0;
		  lexval->datum = new_INT(atoi(yytext)) ;
		  if ( errno ) {
		      p_error( "Value out of range." );
		      raise_exception();
		  }
		  return CONSTANT ;
		}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 307 "scan.l"
{ ADJ_OFFSET() ;
		  errno = 0;
		  lexval->datum = new_REAL(atof(yytext)) ;
		  if ( errno ) {
		      p_error( "Value out of range." );
		      raise_exception();
		  }
		  return CONSTANT ;
		}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 317 "scan.l"
{ ADJ_OFFSET() ;
		  BEGIN(STRINGING) ;
		}
	YY_BREAK
case 30:
/* rule 30 can match eol */
YY_RULE_SETUP
#line 321 "scan.l"
{ 
		  char *s = yytext + yyleng - 2 ;
		  
		  continuing = 1 ;
		  assert(s>=yytext) ;
		  while ( *s != '\\')
		  {
		    assert(s>yytext) ;
		    s-- ;
		  }
		  *s = 0 ;
		  add_to_string(yytext,s-yytext) ;
		}
	YY_BREAK
case 31:
/* rule 31 can match eol */
YY_RULE_SETUP
#line 335 "scan.l"
{ char * s ;
			      int last ;

		  ADJ_OFFSET() ;
		  last = yytext[yyleng-1] ;
		  yytext[yyleng-1] = 0 ;
		  add_to_string(yytext,yyleng-1) ;
		  s = rm_escape(get_string()) ;

		  if ( last == '\n' )
		  {
		    p_error("Unterminated character scalar:\n\"%s", s) ;
		    FREE(s) ;
		    raise_exception() ;
		  }
		  /* found end of string */
		  lexval->cs = strcpy(pmem( strlen(s) + 1 ),s) ;
		  FREE(s) ;
		  BEGIN(0) ;
		  return STRING ;
		}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 357 "scan.l"
{ /* EOF */
		  char *s ;

		  ADJ_OFFSET() ;
		  add_to_string(yytext,yyleng) ;
		  p_error("Unterminated character scalar at EOF:\n\"%s",
			s = rm_escape(get_string())) ;
		  FREE(s) ;
		  raise_exception() ;
		}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 369 "scan.l"
{ ADJ_OFFSET() ;
		  lexval->ival = *yytext == '+' ? OP_ADD : OP_SUB ;
		  return ADDOP ;
		}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 374 "scan.l"
{ ADJ_OFFSET() ;
		  lexval->ival = *yytext == '*' ? OP_MUL : 
		                 *yytext == '/' ? OP_DIV :
				 *yytext == '%' ? OP_MOD :
				                  OP_PROD;
		  return MULOP ;
		}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 382 "scan.l"
{ ADJ_OFFSET() ;
		  
		  switch( yytext[0] )
		  {
		    case '=' :
			lexval->ival = OP_EQ ;
			break ;

		    case '<' :
			lexval->ival = yytext[1] ? OP_LTE : OP_LT ;
			break ;

		    case '>' :
			lexval->ival = yytext[1] ? OP_GTE : OP_GT ;
			break ;

		    case '!' :
			lexval->ival = OP_NE ;
			break ;

		    default :
			wipeout("scanner relop") ;
		  }
		  return RELOP ;
		}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 409 "scan.l"
{ ADJ_OFFSET() ; 
			
		  switch (yytext[0])
                  {
                    case '-':
                      lexval->ival = OP_SUB;
                      break;
                    case '+':
                      lexval->ival = OP_ADD;
                      break;
                    case '*':
                      lexval->ival = OP_MUL;
                      break;
                    case '/':
                      lexval->ival = OP_DIV;
                      break;
                    case '@':
                      lexval->ival = OP_PROD;
                      break;
                    case '%':
                      lexval->ival = OP_MOD;
                      break;
                    default:
                      wipeout ("scanner binop_assign");
                  }

		  return BINOP_ASSIGN ;
		}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 439 "scan.l"
{ ADJ_OFFSET() ;  return SHORT_OR ; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 440 "scan.l"
{ ADJ_OFFSET() ;  return SHORT_AND ; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 442 "scan.l"
{ ADJ_OFFSET() ;  return OR ; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 443 "scan.l"
{ ADJ_OFFSET() ;  return AND ; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 444 "scan.l"
{ ADJ_OFFSET() ;  return CAT ; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 445 "scan.l"
{ ADJ_OFFSET() ;  return TRANS ; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 448 "scan.l"
{ /* anything not covered */
		  ADJ_OFFSET() ;
		  if ( yytext[0] )
		    yyerror("unexpected input character -- ignored") ;
		}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(FLUSH):
case YY_STATE_EOF(STRINGING):
#line 455 "scan.l"
{ if ( !interactive && eof_flag == 0 )
	  { eof_flag = 1 ; return '\n' /* phoney */ ; }
	  else  return EOF ;
	}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 460 "scan.l"
ECHO;
	YY_BREAK
#line 1415 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 148 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 148 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 147);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 460 "scan.l"



typedef struct ps_state
  {
    struct ps_state *link;
    YY_BUFFER_STATE buffer_state;
    FILE *yyin;
    char *input_string;
    char *curr_line;
    int curr_line_no;
    char *curr_file;
    int max_size;
    int eof_flag;

    int flush_flag;
    int interaction;
    int prompting;
    int brace_cnt;
    int flow_cnt;
    CODE_BLOCK code_block;
    struct pm saved_pmem;
    void *jmp_top;
    void *bc_top;
  }
PS_STATE;

extern int interactive;

/*
 * The `stdin_is_interactive' flag may be set in `initialize'.  If it's set,
 * then we use interactive mode for stdin whether it looks like a terminal
 * or not.
 */
extern int stdin_is_interactive;

static PS_STATE *ps_state_list;

/*
 * Use `push_parser_scanner_state' to save the parser's state (the file
 * from which it's reading, along with globals like `interactive', etc.)
 * and change to a new one.
 */

void 
push_parser_scanner_state (fp, file_name)
     FILE *fp;
     char *file_name;
{
  /*
   * If `fp' is NULL, then `file_name' is a pointer to a command string.
   * Otherwise, `fp' points to the input file, and `file_name' is its name.
   * The `file_name' string is not FREE'd.
   */

  PS_STATE *p = MALLOC (sizeof (PS_STATE));

  p->link = ps_state_list;
  ps_state_list = p;

  p->buffer_state = YY_CURRENT_BUFFER;
  p->yyin = yyin;
  yyin = fp;
  p->input_string = input_string;
  input_string = fp ? NULL : file_name;
  yy_switch_to_buffer (yy_create_buffer (yyin, YY_BUF_SIZE));

  p->interaction = interactive;
  p->prompting = issue_prompt;

  issue_prompt = fp && isatty (fileno (fp));
  interactive = issue_prompt || stdin_is_interactive && fp == stdin;

  continuing = 0;

  p->curr_line = curr_line;
  curr_line = (char *) 0;
  p->max_size = max_size;
  max_size = 0;
  p->curr_line_no = curr_line_no;
  curr_line_no = 0;
  p->curr_file = curr_file;
  curr_file = file_name;

  p->eof_flag = eof_flag;
  eof_flag = 0;
  p->flush_flag = flush_flag;
  flush_flag = 0;
  p->brace_cnt = brace_cnt;
  brace_cnt = 0;
  p->flow_cnt = flow_cnt;
  flow_cnt = 0;

  p->code_block = the_code_block;
  new_code_block ();

  p->saved_pmem = active_pmem;
  (void) memset (&active_pmem, 0, sizeof (active_pmem));

  p->jmp_top = jmp_top_push ();
  p->bc_top = bc_top_push ();
}

void 
pop_parser_scanner_state ()
{
  PS_STATE *p;

  assert (ps_state_list);

  p = ps_state_list;
  ps_state_list = p->link;

  yyin = p->yyin;
  input_string = p->input_string;
  yy_delete_buffer (YY_CURRENT_BUFFER);
  if (p->buffer_state)
    yy_switch_to_buffer (p->buffer_state);

  interactive = p->interaction;
  issue_prompt = p->prompting;

  continuing = 0;

  if (curr_line)
    FREE (curr_line);
  curr_line = p->curr_line;
  max_size = p->max_size;
  curr_line_no = p->curr_line_no;
  curr_file = p->curr_file;

  flush_flag = p->flush_flag;
  eof_flag = p->eof_flag;
  brace_cnt = p->brace_cnt;
  flow_cnt = p->flow_cnt;

  FREE (code_base);
  the_code_block = p->code_block;

  free_all_pmem ();
  active_pmem = p->saved_pmem;

  jmp_top_pop (p->jmp_top);
  bc_top_pop (p->bc_top);

  FREE (p);
}


/*----------  process escape characters in strings ----*/


#define isoctal(x)  ((x)>='0'&&(x)<='7')

#define  hex_value(x)   ((x)<='F'?(x)-'A'+10:(x)-'a'+10)


/* process one , two or three octal digits
   moving a pointer forward by reference */
static int octal( start_p )
  char **start_p ;
{ register char *p = *start_p ;
  register unsigned x ;

  x = *p++ - '0' ;
  if ( isoctal(*p) )
  {
    x = (x<<3) + *p++ - '0' ;
    if ( isoctal(*p) )   x = (x<<3) + *p++ - '0' ;
  }
  *start_p = p ;
  return  x & 0xff ;
}

/* process one or two hex digits
   moving a pointer forward by reference */

static int  hex( start_p )
  char **start_p ;
{ register unsigned char *p = (unsigned char*) *start_p ;
  register unsigned x ;

  if ( isdigit(*p) ) x = *p - '0' ;
  else  x = hex_value(*p) ;
  p++ ;

  if ( isdigit(*p) ) x = (x<<4) + *p++ - '0' ;
  else
  if ( isxdigit(*p) )
  { x = (x<<4) + hex_value(*p) ; p++ ; }

  *start_p = (char *) p ;
  return x ;
}

#define  NUM_ESCAPE_CHARS    8

static struct { char in , out ; } 
escape_test[NUM_ESCAPE_CHARS+1] = {
    'n' , '\n',		/* newline	   */
    't' , '\t',		/* tab		   */
    'f' , '\f',		/* formfeed	   */
    'b' , '\b',		/* backspace	   */
    'r' , '\r',		/* carriage return */
    'a' , '\07',	/* bell		   */
    'v' , '\013',	/* vertical tab	   */
    'e' , '\033',	/* escape	   */
    0 , 0
};

/* all other escaped chars stand for themselves */


/* process the escape characters in a string, in place . */

static char *rm_escape(s)
  char *s ;
{ char *p, *q ;
  char *t ;
  int i ;

  q = p = s ;

  while ( *p )
      if ( *p == '\\' )
      { 
        escape_test[NUM_ESCAPE_CHARS].in = * ++p ; /* sentinel */
        i = 0 ;
        while ( escape_test[i].in != *p )  i++ ;

        if ( i != NUM_ESCAPE_CHARS )  /* in table */
        { 
          p++ ; *q++ = escape_test[i].out ;
        }
        else
        if ( isoctal(*p) ) 
        { /* keep p in register */
          t = p ;  *q++ = octal(&t) ; p = t ;
        }
        else
        if ( *p == 'x' && isxdigit(*(unsigned char*)(p+1)) )
        {
          t = p+1 ; *q++ = hex(&t) ; p = t ;
        }
	else
	if ( *p == 0 )  *q++ = '\\' ; 
        else  /* not an escape sequence */
           *q++ = *p++ ;
      }
      else  *q++ = *p++ ;

  *q = 0 ;
  return s ;
}


/* stuff to put multiple line strings together */

static char *the_string ; /* built it here */
static int len ;  /* strlen(the_string) */

static char *get_string()
{
  char *s = the_string ;
  the_string = (char *) 0 ;
  len = 0 ;
  return s ;
}

static void 
add_to_string( s,  slen) 
  char *s ;
  int slen ;
{
    char *new = MALLOC(len+slen+1) ;
    if ( the_string )
    { (void) memcpy(new, the_string, len) ;
      FREE(the_string) ;
    }
    (void) strcpy(new+len,s) ;
    len += slen ;
    the_string = new ;
}

